sandbox_mode = "workspace-write"
approval_policy="never"
model = "gpt-5.3-codex"
model_reasoning_effort = "medium"
personality = "pragmatic"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
